#!/usr/bin/env python3
# BIBLIOTEAS
#
from os import system
from time import sleep
#from libs import upload
#from libs import update
#
#


def menu():
    system("clear")
    print("""
    ╔═╗╦ ╦╔╦╗╔═╗  ╔═╗╦╔╦╗
    ╠═╣║ ║ ║ ║ ║  ║ ╦║ ║ 
    ╩ ╩╚═╝ ╩ ╚═╝  ╚═╝╩ ╩ \n
[01] - project upload
[02] - Update Project
[03] - Credits
[99] - Exit
		""")
    cmd = str(input("===> "))
    if cmd == '1':
        fun_upload()
    elif cmd == '2':
        fun_update()
    else:
        print("Comando Inválido!!!")
        sleep(2)


def fun_upload():
    system('clear')
    print("""
	╦ ╦╔═╗╦  ╔═╗╔═╗╔╦╗  ╔═╗╦═╗╔═╗ ╦╔═╗╔═╗╔╦╗
	║ ║╠═╝║  ║ ║╠═╣ ║║  ╠═╝╠╦╝║ ║ ║║╣ ║   ║ 
	╚═╝╩  ╩═╝╚═╝╩ ╩═╩╝  ╩  ╩╚═╚═╝╚╝╚═╝╚═╝ ╩ \n
- If you have already used these commands in your terminal, go to option [01].

[commands: git config --global user.email “you_email@gmail.com" && git config --global user.name “you_name_in_github”]\n

[01] - already logged in
[02] - not logged in
	
	""")
    cmd = str(input('===> '))
    if cmd == '1':
        system('clear')
        print("""
    ╔═╗╦ ╦╔╦╗╔═╗  ╔═╗╦╔╦╗
    ╠═╣║ ║ ║ ║ ║  ║ ╦║ ║ 
    ╩ ╩╚═╝ ╩ ╚═╝  ╚═╝╩ ╩ \n
		""")
        system('git init')
        sleep(1)
        system('git status')
        sleep(1)
        system('git add .')
        sleep(1)
        system('git status')
        sleep(1)
        system('git commit -m "first commit"')
        sleep(1)
        git_remote = str(input('[+] - Digite o link do seu repositorio: '))
        system(f'git remote add origin "{git_remote}"')
        sleep(1)
        branch = str(
            input('[+] - Digite qual branch quer usar (main/master): '))
        system(f'git push origin {branch}')
    elif cmd == '2':
        system('clear')
        print("""
    ╔═╗╦ ╦╔╦╗╔═╗  ╔═╗╦╔╦╗
    ╠═╣║ ║ ║ ║ ║  ║ ╦║ ║ 
    ╩ ╩╚═╝ ╩ ╚═╝  ╚═╝╩ ╩ \n
		""")
        email = str(input('[+] - Digite seu email: '))
        system(f'git config --global user.email "{email}"')
        sleep(1)
        user = str(input('[+] - Digite seu Usuario: '))
        system(f'git config --global user.name “{user}”')
        sleep(1)
        system('git init')
        sleep(1)
        system('git status')
        sleep(1)
        system('git add .')
        sleep(1)
        system('git status')
        sleep(1)
        system('git commit -m "first commit"')
        sleep(1)
        git_remote = str(input('[+] - Digite o link do seu repositorio: '))
        system(f'git remote add origin "{git_remote}"')
        sleep(1)
        branch = str(
            input('[+] - Digite qual branch quer usar (main/master): '))
        system(f'git push origin {branch}')


def fun_update():
    system('clear')
    print("""
	╦ ╦╔═╗╔╦╗╔═╗╔╦╗╔═╗  ╔═╗╦═╗╔═╗╔╦╗  ╔╦╗╦ ╦╔═╗  ╦═╗╔═╗╔═╗╔═╗╔═╗╦╔╦╗╔═╗╦═╗╦ ╦
    ║ ║╠═╝ ║║╠═╣ ║ ║╣   ╠╣ ╠╦╝║ ║║║║   ║ ╠═╣║╣   ╠╦╝║╣ ╠═╝║ ║╚═╗║ ║ ║ ║╠╦╝╚╦╝
    ╚═╝╩  ═╩╝╩ ╩ ╩ ╚═╝  ╚  ╩╚═╚═╝╩ ╩   ╩ ╩ ╩╚═╝  ╩╚═╚═╝╩  ╚═╝╚═╝╩ ╩ ╚═╝╩╚═ ╩ 
	""")
    system('git add .')
    sleep(1)
    commit = str(input('[+] - Texto para o commit: '))
    system(f'git commit -m "{commit}"')
    sleep(1)
    branch = str(input('[+] - Digite qual branch quer usar (main/master): '))
    system(f'git push -u origin {branch}')


menu()
